ALTER TABLE "MonthlyPlan"
  ADD COLUMN IF NOT EXISTS "memoryImageUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "memoryCaption" VARCHAR(500) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "memoryImageMeta" JSONB;
